version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: deepseek-server
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: deepseek-ui
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  ollama_data: